# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDb

  target 'TMDbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire', '~> 5.0.0.beta.1'
  pod 'SDWebImage', '~> 4.0'

end
